# See https://github.com/crate-ci/typos/blob/master/docs/reference.md to configure typos
[default.extend-words]
edn = "edn"
juxt = "juxt"
OT = "OT"     # bsongOT
[files]
extend-exclude = ["Changelog*.md", "Changelog*.org"]
